import {
  RiBarChartFill,
  RiChat1Fill,
  RiGroupFill,
  RiMegaphoneFill,
} from "@remixicon/react"

import type {
  Attendee,
  Equipment,
  Report,
  Store,
  StoreDetail,
  TicketDataPoint,
} from "./types"

// ── Pessoas ───────────────────────────────────────────────────
export const TECHS: Record<string, Attendee> = {
  joao:    { name: "João Silva",      initials: "JS", color: "#3b82f6" },
  maria:   { name: "Maria Oliveira",  initials: "MO", color: "#ec4899" },
  pedro:   { name: "Pedro Santos",    initials: "PS", color: "#f59e0b" },
  ana:     { name: "Ana Lima",        initials: "AL", color: "#10b981" },
  carlos:  { name: "Carlos Ferreira", initials: "CF", color: "#8b5cf6" },
  rogerio: { name: "Rogério Alves",   initials: "RA", color: "#f97316" },
}

export const MANAGERS: Record<string, Attendee> = {
  eduardo: { name: "Eduardo Klein",  initials: "EK", color: "#06b6d4" },
  sofia:   { name: "Sofia Lima",     initials: "SL", color: "#84cc16" },
  amanda:  { name: "Amanda Martins", initials: "AM", color: "#6366f1" },
  jose:    { name: "José Ribeiro",   initials: "JR", color: "#14b8a6" },
  andre:   { name: "André Carvalho", initials: "AC", color: "#f43f5e" },
  marcos:  { name: "Marcos Santos",  initials: "MS", color: "#a855f7" },
}

export const TECHS_LIST: Attendee[] = Object.values(TECHS)
export const MANAGERS_LIST: Attendee[] = Object.values(MANAGERS)
export const PEOPLE_CATALOG: Attendee[] = [...TECHS_LIST, ...MANAGERS_LIST]

// ── Stores (catálogo) ─────────────────────────────────────────
export const stores: Store[] = [
  {
    slug: "retention",
    name: "Quitandaria Caruaru",
    description: "Tracks user retention over weekly and monthly intervals.",
    lastEdited: "1 day ago",
    authorInitials: "EK",
    icon: RiGroupFill,
    image: "/caruaru.jpg",
  },
  {
    slug: "revenue",
    name: "Quitandaria Aflitos",
    description:
      "Analyzes revenue generated by employees based on their roles and contributions.",
    lastEdited: "2 days ago",
    authorInitials: "SL",
    icon: RiBarChartFill,
    image: "/aflitos.jpg",
  },
  {
    slug: "active-users",
    name: "Quitandaria Espinheiro",
    description:
      "Provides a snapshot of active users on the platform as of today.",
    lastEdited: "14 hours ago",
    authorInitials: "AM",
    icon: RiGroupFill,
    image: "/espinheiro.jpg",
  },
  {
    slug: "product-sales",
    name: "Quitandaria Hipódromo",
    description:
      "Details the sales performance of products over a quarterly timeframe.",
    lastEdited: "4 days ago",
    authorInitials: "JR",
    icon: RiBarChartFill,
    image: "/hipodromo.jpg",
  },
  {
    slug: "customer-feedback",
    name: "Quitandaria Bairro Novo",
    description:
      "Analyzes customer feedback survey results to gauge customer satisfaction.",
    lastEdited: "5 days ago",
    authorInitials: "AC",
    icon: RiChat1Fill,
    image: "/bairro-novo.jpg",
  },
  {
    slug: "marketing-campaign-1",
    name: "Quitandaria Casa Caiada",
    description:
      "Examines the performance of marketing campaigns to return on investment (ROI).",
    lastEdited: "6 days ago",
    authorInitials: "MS",
    icon: RiMegaphoneFill,
    image: "/casa-caiada.jpg",
  },
  {
    slug: "marketing-campaign-2",
    name: "Quitandaria Rio Doce",
    description:
      "Examines the performance of marketing campaigns to return on investment (ROI).",
    lastEdited: "6 days ago",
    authorInitials: "MS",
    icon: RiMegaphoneFill,
    image: "/rio-doce.jpg",
  },
  {
    slug: "marketing-campaign-3",
    name: "Quitandaria Janga",
    description:
      "Examines the performance of marketing campaigns to return on investment (ROI).",
    lastEdited: "6 days ago",
    authorInitials: "MS",
    icon: RiMegaphoneFill,
    image: "/janga.jpg",
  },
]

// ── Mock auxiliares de Store detail ───────────────────────────
const baseTicketHistory: TicketDataPoint[] = [
  { period: "Nov/25", chamados: 4 },
  { period: "Dez/25", chamados: 7 },
  { period: "Jan/26", chamados: 3 },
  { period: "Fev/26", chamados: 9 },
  { period: "Mar/26", chamados: 5 },
  { period: "Abr/26", chamados: 6 },
  { period: "Mai/26", chamados: 2 },
  { period: "Jun/26", chamados: 8 },
  { period: "Jul/26", chamados: 11 },
  { period: "Ago/26", chamados: 4 },
  { period: "Set/26", chamados: 6 },
  { period: "Out/26", chamados: 3 },
]

const baseEquipment: Equipment[] = [
  {
    id: "eq-001",
    name: "Ar Condicionado Split 24.000 BTU",
    type: "Climatização",
    serial: "AC-2023-0041",
    status: "operacional",
    lastMaintenance: "15/03/2026",
  },
  {
    id: "eq-002",
    name: "Sistema CFTV – NVR 16 Canais",
    type: "Segurança",
    serial: "NVR-2022-0018",
    status: "em_manutencao",
    lastMaintenance: "01/04/2026",
  },
  {
    id: "eq-003",
    name: "Nobreak 3kVA Senoidal",
    type: "Energia",
    serial: "NB-2021-0093",
    status: "operacional",
    lastMaintenance: "20/02/2026",
  },
  {
    id: "eq-004",
    name: "Terminal PDV – Caixa 01",
    type: "TI",
    serial: "PDV-2024-0011",
    status: "operacional",
    lastMaintenance: "10/04/2026",
  },
  {
    id: "eq-005",
    name: "Terminal PDV – Caixa 02",
    type: "TI",
    serial: "PDV-2024-0012",
    status: "inativo",
    lastMaintenance: "10/04/2026",
  },
  {
    id: "eq-006",
    name: "Gerador a Diesel 15kVA",
    type: "Energia",
    serial: "GE-2020-0005",
    status: "operacional",
    lastMaintenance: "05/01/2026",
  },
]

const baseReports: Report[] = [
  {
    id: "rep-001",
    title: "Manutenção Preventiva – Outubro/2026",
    date: "31/10/2026",
    type: "Preventiva",
    url: "#",
  },
  {
    id: "rep-002",
    title: "Chamados Técnicos – 3º Trimestre 2026",
    date: "30/09/2026",
    type: "Chamados",
    url: "#",
  },
  {
    id: "rep-003",
    title: "Inventário de Equipamentos – Set/2026",
    date: "30/09/2026",
    type: "Inventário",
    url: "#",
  },
  {
    id: "rep-004",
    title: "Manutenção Corretiva – Ago/2026",
    date: "31/08/2026",
    type: "Corretiva",
    url: "#",
  },
  {
    id: "rep-005",
    title: "Relatório Semestral – 1º Semestre 2026",
    date: "30/06/2026",
    type: "Semestral",
    url: "#",
  },
]

// ── Detalhes por loja ─────────────────────────────────────────
const storeDetails: Record<string, StoreDetail> = {
  retention: {
    address:
      "R. Visc. de Inhaúma, 1333 - Maurício de Nassau, Caruaru - PE, 55014-410",
    phone: "(081) 98243-1005",
    manager: "Eduardo Klein",
    region: "Leste",
    status: "ativo",
    ticketHistory: baseTicketHistory,
    equipment: baseEquipment,
    reports: baseReports,
  },
  revenue: {
    address: "Rua Oscar Freire, 900 – Jardins, São Paulo – SP",
    phone: "(11) 97654-3210",
    manager: "Sofia Lima",
    region: "Oeste",
    status: "em_reforma",
    ticketHistory: baseTicketHistory.map((d) => ({
      ...d,
      chamados: Math.round(d.chamados * 1.4),
    })),
    equipment: baseEquipment,
    reports: baseReports,
  },
  "active-users": {
    address:
      "Shopping Morumbi, Av. Roque Petroni Jr. 1089 – São Paulo – SP",
    phone: "(11) 98888-1234",
    manager: "Amanda Martins",
    region: "Norte",
    status: "ativo",
    ticketHistory: baseTicketHistory.map((d) => ({
      ...d,
      chamados: Math.max(1, Math.round(d.chamados * 0.7)),
    })),
    equipment: baseEquipment,
    reports: baseReports,
  },
  "product-sales": {
    address: "Av. das Nações Unidas, 3003 – Barra Funda, São Paulo – SP",
    phone: "(11) 92222-9876",
    manager: "José Ribeiro",
    region: "Sul",
    status: "ativo",
    ticketHistory: baseTicketHistory,
    equipment: baseEquipment,
    reports: baseReports,
  },
  "customer-feedback": {
    address: "Rua da Consolação, 247 – Consolação, São Paulo – SP",
    phone: "(11) 93333-6543",
    manager: "André Carvalho",
    region: "Centro",
    status: "ativo",
    ticketHistory: baseTicketHistory.map((d) => ({
      ...d,
      chamados: Math.max(1, Math.round(d.chamados * 0.9)),
    })),
    equipment: baseEquipment,
    reports: baseReports,
  },
  "marketing-campaign-1": {
    address: "Av. Rebouças, 3970 – Pinheiros, São Paulo – SP",
    phone: "(11) 94444-1111",
    manager: "Marcos Santos",
    region: "Leste",
    status: "ativo",
    ticketHistory: baseTicketHistory,
    equipment: baseEquipment,
    reports: baseReports,
  },
  "marketing-campaign-2": {
    address: "Rua Augusta, 1200 – Consolação, São Paulo – SP",
    phone: "(11) 95555-2222",
    manager: "Marcos Santos",
    region: "Oeste",
    status: "inativo",
    ticketHistory: baseTicketHistory.map((d) => ({ ...d, chamados: 0 })),
    equipment: baseEquipment.map((e) => ({ ...e, status: "inativo" as const })),
    reports: baseReports.slice(0, 2),
  },
  "marketing-campaign-3": {
    address: "Al. Santos, 700 – Cerqueira César, São Paulo – SP",
    phone: "(11) 96666-3333",
    manager: "Marcos Santos",
    region: "Norte",
    status: "ativo",
    ticketHistory: baseTicketHistory.map((d) => ({
      ...d,
      chamados: Math.round(d.chamados * 1.2),
    })),
    equipment: baseEquipment,
    reports: baseReports,
  },
}

const fallback: StoreDetail = {
  address: "Endereço não cadastrado",
  phone: "—",
  manager: "—",
  region: "—",
  status: "ativo",
  ticketHistory: baseTicketHistory,
  equipment: baseEquipment,
  reports: baseReports,
}

export function getStoreDetail(slug: string): StoreDetail {
  return storeDetails[slug] ?? fallback
}
