import {
  RiBarChartFill,
  RiChat1Fill,
  RiGroupFill,
  RiMegaphoneFill,
} from '@remixicon/react';
import { ElementType } from 'react';

export type Store = {
  slug: string;
  name: string;
  description: string;
  lastEdited: string;
  authorInitials: string;
  icon: ElementType;
  image: string;
};

export const stores: Store[] = [
  {
    slug: 'retention',
    name: 'Quitandaria Caruaru',
    description: 'Tracks user retention over weekly and monthly intervals.',
    lastEdited: '1 day ago',
    authorInitials: 'EK',
    icon: RiGroupFill,
    image: '/caruaru.jpg',
  },
  {
    slug: 'revenue',
    name: 'Quitandaria Aflitos',
    description:
      'Analyzes revenue generated by employees based on their roles and contributions.',
    lastEdited: '2 days ago',
    authorInitials: 'SL',
    icon: RiBarChartFill,
    image: '/aflitos.jpg',
  },
  {
    slug: 'active-users',
    name: 'Quitandaria Espinheiro',
    description:
      'Provides a snapshot of active users on the platform as of today.',
    lastEdited: '14 hours ago',
    authorInitials: 'AM',
    icon: RiGroupFill,
    image: '/espinheiro.jpg',
  },
  {
    slug: 'product-sales',
    name: 'Quitandaria Hipódromo',
    description:
      'Details the sales performance of products over a quarterly timeframe.',
    lastEdited: '4 days ago',
    authorInitials: 'JR',
    icon: RiBarChartFill,
    image: '/hipodromo.jpg',
  },
  {
    slug: 'customer-feedback',
    name: 'Quitandaria Bairro Novo',
    description:
      'Analyzes customer feedback survey results to gauge customer satisfaction.',
    lastEdited: '5 days ago',
    authorInitials: 'AC',
    icon: RiChat1Fill,
    image: '/bairro-novo.jpg',
  },
  {
    slug: 'marketing-campaign-1',
    name: 'Quitandaria Casa Caiada',
    description:
      'Examines the performance of marketing campaigns to return on investment (ROI).',
    lastEdited: '6 days ago',
    authorInitials: 'MS',
    icon: RiMegaphoneFill,
    image: '/casa-caiada.jpg',
  },
  {
    slug: 'marketing-campaign-2',
    name: 'Quitandaria Rio Doce',
    description:
      'Examines the performance of marketing campaigns to return on investment (ROI).',
    lastEdited: '6 days ago',
    authorInitials: 'MS',
    icon: RiMegaphoneFill,
    image: '/rio-doce.jpg',
  },
  {
    slug: 'marketing-campaign-3',
    name: 'Quitandaria Janga',
    description:
      'Examines the performance of marketing campaigns to return on investment (ROI).',
    lastEdited: '6 days ago',
    authorInitials: 'MS',
    icon: RiMegaphoneFill,
    image: '/janga.jpg',
  },
];
